### ISSUE TITLE
Usage of a preparse field in cp table view causes an error

### ISSUE THREAD

**Issue by knufri** [jalendport/craft-preparse#101]
First of all I want to say thank you to @jalendport to upgrade this plugin for Craft 5. I upgraded a site from Craft 4 to 5 and also the preparse plugin. It works so far but when I use the field in the table preview it causes an 500 error:

<img width="458" alt="Bildschirmfoto 2024-07-15 um 09 51 01" src="https://github.com/user-attachments/assets/faea7ef4-7bff-48fb-a8dc-33b98267f7c0">

```
Twig\Error\RuntimeError: Calling unknown method: jalendport\preparse\fields\PreparseFieldType::getTableAttributeHtml() in /Users/jan/Sites/jswebdev/versteigerungskalender.de/vendor/craftcms/cms/src/templates/_elements/tableview/elements.twig:107
```

Steps to reproduce:

1. Add an preparse field to an entry type
2. Try to use it in the table view in the control panel

```
PHP version - 8.2.21
MariaDB - 11.2.2
Craft Pro - 5.2.6
Preparse - 3.0.0-alpha.1
```

**Comment by jalendport** [comment]
Thanks for reporting; fixed in `3.0.0-alpha.2`... 🙌

**Comment by knufri** [comment]
WOW @jalendport this was quick 😄

**Comment by jalendport** [comment]
@knufri I had an hour to wait at the airport this morning so it worked out perfectly 👌😁
